project:
  type: website
  output-dir: docs

website:
  title: "DataScouteR"
  navbar:
    left:
      - text: "Guide"
        href: index.qmd
      - text: "Attributes"
        href: attributes.qmd

format:
  html:
    theme: journal
    toc: true
    css: styles.css



