project:
  type: website
  output-dir: docs

website:
  title: "DataScouteR"
  navbar:
    left:
      - text: "Guide"
        href: index.qmd

format:
  html:
    theme: darkly
    toc: true
    css: styles.css



